import json
import os
import io
import sqlite3
import datetime

DB_CONFIG_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'db_config.json')


def load_config():
    try:
        with open(DB_CONFIG_PATH) as f:
            return json.load(f)
    except Exception:
        return {"db_type": "sqlite"}


def save_config(cfg):
    with open(DB_CONFIG_PATH, 'w') as f:
        json.dump(cfg, f, indent=2)


def get_db_uri():
    cfg = load_config()
    if cfg.get('db_type') == 'mysql':
        h = cfg.get('mysql_host', 'localhost')
        p = cfg.get('mysql_port', 3306)
        d = cfg.get('mysql_database', '')
        u = cfg.get('mysql_user', '')
        pw = cfg.get('mysql_password', '')
        return f'mysql+pymysql://{u}:{pw}@{h}:{p}/{d}'
    db_path = os.path.join(os.path.dirname(DB_CONFIG_PATH), 'resume_app.db')
    return f'sqlite:///{db_path}'


def test_mysql_connection(host, port, database, user, password):
    try:
        import pymysql
        conn = pymysql.connect(
            host=host,
            port=int(port),
            database=database,
            user=user,
            password=password,
            connect_timeout=5,
        )
        conn.close()
        return True, None
    except Exception as e:
        return False, str(e)


def _escape_sql_value(val):
    if val is None:
        return 'NULL'
    if isinstance(val, bool):
        return '1' if val else '0'
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, (datetime.datetime, datetime.date)):
        return f"'{val.isoformat()}'"
    s = str(val).replace("\\", "\\\\").replace("'", "\\'")
    return f"'{s}'"


def export_as_sqlite():
    """Return a bytes object containing a SQLite .db dump (SQL text)."""
    cfg = load_config()
    db_type = cfg.get('db_type', 'sqlite')

    if db_type == 'sqlite':
        db_path = os.path.join(os.path.dirname(DB_CONFIG_PATH), 'resume_app.db')
        conn = sqlite3.connect(db_path)
        lines = list(conn.iterdump())
        conn.close()
        return '\n'.join(lines).encode('utf-8')

    # MySQL source → generate SQLite-compatible SQL
    return _export_mysql_to_sqlite_sql(cfg)


def _export_mysql_to_sqlite_sql(cfg):
    import pymysql
    conn = pymysql.connect(
        host=cfg.get('mysql_host', 'localhost'),
        port=int(cfg.get('mysql_port', 3306)),
        database=cfg.get('mysql_database', ''),
        user=cfg.get('mysql_user', ''),
        password=cfg.get('mysql_password', ''),
    )
    cur = conn.cursor()
    cur.execute("SHOW TABLES")
    tables = [row[0] for row in cur.fetchall()]

    buf = io.StringIO()
    buf.write("BEGIN TRANSACTION;\n")
    for table in tables:
        cur.execute(f"DESCRIBE `{table}`")
        cols = cur.fetchall()
        col_defs = []
        for col in cols:
            name, typ, null, key, default, extra = col
            sqlite_type = 'TEXT'
            t = typ.upper()
            if any(x in t for x in ('INT',)):
                sqlite_type = 'INTEGER'
            elif any(x in t for x in ('FLOAT', 'DOUBLE', 'DECIMAL', 'NUMERIC')):
                sqlite_type = 'REAL'
            pk = ' PRIMARY KEY' if key == 'PRI' else ''
            nn = ' NOT NULL' if null == 'NO' and key != 'PRI' else ''
            col_defs.append(f'  "{name}" {sqlite_type}{pk}{nn}')
        buf.write(f'CREATE TABLE IF NOT EXISTS "{table}" (\n')
        buf.write(',\n'.join(col_defs))
        buf.write('\n);\n')

        col_names = [c[0] for c in cols]
        cur.execute(f"SELECT * FROM `{table}`")
        rows = cur.fetchall()
        for row in rows:
            vals = ', '.join(_escape_sql_value(v) for v in row)
            cols_str = ', '.join(f'"{c}"' for c in col_names)
            buf.write(f'INSERT INTO "{table}" ({cols_str}) VALUES ({vals});\n')
    buf.write("COMMIT;\n")
    conn.close()
    return buf.getvalue().encode('utf-8')


def export_as_mysql():
    """Return bytes of a MySQL-compatible SQL dump."""
    cfg = load_config()
    db_type = cfg.get('db_type', 'sqlite')

    if db_type == 'mysql':
        return _export_mysql_dump(cfg)
    return _export_sqlite_to_mysql_sql()


def _export_sqlite_to_mysql_sql():
    db_path = os.path.join(os.path.dirname(DB_CONFIG_PATH), 'resume_app.db')
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
    tables = [row[0] for row in cur.fetchall()]

    buf = io.StringIO()
    buf.write("-- MySQL dump generated by AI Resume App\n")
    buf.write("SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n")

    for table in tables:
        cur.execute(f"PRAGMA table_info(`{table}`)")
        cols_info = cur.fetchall()

        buf.write(f"DROP TABLE IF EXISTS `{table}`;\n")
        buf.write(f"CREATE TABLE `{table}` (\n")
        col_defs = []
        pk_col = None
        for col in cols_info:
            cid, name, typ, notnull, dflt, pk = col
            mysql_type = 'LONGTEXT'
            t = typ.upper()
            if 'INT' in t:
                mysql_type = 'INT'
            elif any(x in t for x in ('REAL', 'FLOAT', 'DOUBLE', 'NUMERIC')):
                mysql_type = 'DOUBLE'
            if pk:
                pk_col = name
            ai = ' AUTO_INCREMENT' if pk else ''
            nn = ' NOT NULL' if notnull else ''
            col_defs.append(f'  `{name}` {mysql_type}{nn}{ai}')
        if pk_col:
            col_defs.append(f'  PRIMARY KEY (`{pk_col}`)')
        buf.write(',\n'.join(col_defs))
        buf.write('\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n\n')

        col_names = [c[1] for c in cols_info]
        cur.execute(f"SELECT * FROM `{table}`")
        rows = cur.fetchall()
        if rows:
            buf.write(f"INSERT INTO `{table}` (`{'`, `'.join(col_names)}`) VALUES\n")
            row_strs = []
            for row in rows:
                vals = ', '.join(_escape_sql_value(v) for v in row)
                row_strs.append(f'  ({vals})')
            buf.write(',\n'.join(row_strs))
            buf.write(';\n\n')

    buf.write("SET FOREIGN_KEY_CHECKS=1;\n")
    conn.close()
    return buf.getvalue().encode('utf-8')


def _export_mysql_dump(cfg):
    import pymysql
    conn = pymysql.connect(
        host=cfg.get('mysql_host', 'localhost'),
        port=int(cfg.get('mysql_port', 3306)),
        database=cfg.get('mysql_database', ''),
        user=cfg.get('mysql_user', ''),
        password=cfg.get('mysql_password', ''),
    )
    cur = conn.cursor()
    cur.execute("SHOW TABLES")
    tables = [row[0] for row in cur.fetchall()]

    buf = io.StringIO()
    buf.write("-- MySQL dump generated by AI Resume App\n")
    buf.write("SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n")

    for table in tables:
        cur.execute(f"SHOW CREATE TABLE `{table}`")
        create_stmt = cur.fetchone()[1]
        buf.write(f"DROP TABLE IF EXISTS `{table}`;\n")
        buf.write(create_stmt + ";\n\n")

        cur.execute(f"DESCRIBE `{table}`")
        cols = [c[0] for c in cur.fetchall()]
        cur.execute(f"SELECT * FROM `{table}`")
        rows = cur.fetchall()
        if rows:
            buf.write(f"INSERT INTO `{table}` (`{'`, `'.join(cols)}`) VALUES\n")
            row_strs = []
            for row in rows:
                vals = ', '.join(_escape_sql_value(v) for v in row)
                row_strs.append(f'  ({vals})')
            buf.write(',\n'.join(row_strs))
            buf.write(';\n\n')

    buf.write("SET FOREIGN_KEY_CHECKS=1;\n")
    conn.close()
    return buf.getvalue().encode('utf-8')
